language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.8
  - 3.10
  - 3.11
env:
  - DJANGO=1.8
  - DJANGO=1.9
  - DJANGO=1.10
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=3.2
  - DJANGO=4.0.6
  - DJANGO=4.1.3
matrix:
  exclude:
    # Python/Django combinations that aren't officially supported
    - { python: 3.6, env: DJANGO=1.8 }
    - { python: 3.6, env: DJANGO=1.9 }
    - { python: 3.6, env: DJANGO=1.10 }
    - { python: 2.7, env: DJANGO=2.0 }
  include:
    - { python: 3.6, env: TOXENV=flake8 }

install:
  - pip install tox-travis
script:
  - tox
